#数据源设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.119.126.7:3306/yg_admin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: osyVW>GM+9<b
    type: com.alibaba.druid.pool.DruidDataSource
  #静态资源设置
  web:
    resources:
      static-locations: classpath:/static,classpath:/templates
  #thymeleaf配置
  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    mode: HTML
  #热部署
  devtools:
    restart:
      enabled: true
#根路径设置
server:
  servlet:
    context-path: /

#mybatis配置
#mybatis:
#  mapper-locations: classpath:/com/youguang/mapper/*.xml
#  type-aliases-package: com.youguang.admin.mapper
mybatis-plus:
  mapper-locations: classpath:/com/youguang/mapper/*.xml
  type-aliases-package: com.youguang.admin.mapper